package gabywald.biosilico.exceptions;

import gabywald.global.exceptions.GenericException;

/**
 * This Exception is generated by the constructor of class Triplet, 
 * If paramater is not long enough. 
 * @author Gabriel Chandesris (2009-2010)
 * @see gabywald.cellmodel.model.Triplet#Triplet(String)
 */
@SuppressWarnings("serial")
public class TripletException extends GenericException { 
	/**
	 * Default Constructor with message
	 * @param request (String)
	 */
	public TripletException(String request) { super(request); }
}
